import {test} from 'node:test';
import assert from 'node:assert/strict';
import {withOwner,loan,contact,source} from './support/session.mjs';
test('catalog and one-time obligations are owner-bound atomic revisioned and retry-safe',async()=>withOwner('records',async({user,call,command,root})=>{
 const person=await call('saveCatalog',command('contact-1',{kind:'contact',id:null,expectedRevision:null,values:contact()}));
 const cash=await call('saveCatalog',command('source-1',{kind:'source',id:null,expectedRevision:null,values:source()}));
 const payload=command('loan-1',loan({contactId:person.id,paymentSourceId:cash.id}));
 const [created,replayed]=await Promise.all([call('createObligation',payload),call('createObligation',payload)]);
 assert.deepEqual(created,replayed);
 const parentRef=root.collection('obligations').doc(created.obligationId);
 const instanceRef=root.collection('obligationInstances').doc(created.obligationInstanceId);
 const parent=(await parentRef.get()).data();const instance=(await instanceRef.get()).data();
 assert.equal(parent.timezone,'Asia/Manila');
 assert.equal(parent.userId,user.uid);assert.equal(parent.originalAmountMinor,1_000_000);assert.equal(parent.remainingMinor,1_000_000);assert.equal(parent.totalPaidMinor,0);assert.equal(parent.contactSnapshot.displayName,'John');
 assert.equal(instance.obligationId,created.obligationId);assert.equal(instance.amountMinor,1_000_000);assert.equal(instance.remainingMinor,1_000_000);
 assert.equal((await root.collection('obligations').get()).size,1);assert.equal((await root.collection('activities').where('type','==','obligationCreated').get()).size,1);
 assert.equal((await root.collection('ledgerState').doc('current').get()).data().revision,3);
 await assert.rejects(call('createObligation',{...payload,expectedOwnerUid:'bob'}),{code:'functions/permission-denied'});
 await assert.rejects(call('createObligation',{...payload,payload:loan({amountMinor:200_000})}),{code:'functions/already-exists'});
 await assert.rejects(call('createObligation',command('missing-contact',loan({contactId:'another-owner-contact'}))),{code:'functions/failed-precondition'});
 await assert.rejects(call('createObligation',command('unknown-category',loan({categoryId:'missing'}))),{code:'functions/failed-precondition'});
 assert.equal((await root.collection('obligations').get()).size,1);
 const unknown=await call('createObligation',command('no-due',loan({dueDate:null,currency:'USD',amountMinor:50000})));
 assert.equal((await root.collection('obligationInstances').doc(unknown.obligationInstanceId).get()).data().dueDate,null);
 const overdue=await call('createObligation',command('past-due',loan({dueDate:'2020-01-02'})));
 assert.equal((await root.collection('obligations').doc(overdue.obligationId).get()).data().financialStatus,'overdue');
 assert.equal((await root.collection('obligationInstances').doc(overdue.obligationInstanceId).get()).data().financialStatus,'overdue');
 await assert.rejects(call('createObligation',command('future-origination',loan({originationDate:'2199-01-01',dueDate:null}))),{code:'functions/invalid-argument'});
 const edit={...loan({contactId:person.id,paymentSourceId:cash.id}),obligationId:created.obligationId,expectedRevision:1,title:'Updated loan',description:'Borrowed money',notes:'Due date agreed',dueDate:'2026-11-15'};
 await call('editObligation',command('edit-1',edit));
 assert.equal((await parentRef.get()).data().revision,2);assert.equal((await instanceRef.get()).data().yearMonth,'2026-11');
 await assert.rejects(call('editObligation',command('stale-edit',edit)),{code:'functions/aborted'});
 await call('editObligation',command('correct-principal',{...edit,expectedRevision:2,amountMinor:900_000,currency:'JPY'}));
 assert.equal((await parentRef.get()).data().originalAmountMinor,900_000);
 assert.equal((await instanceRef.get()).data().amountMinor,900_000);
 assert.equal((await parentRef.get()).data().remainingMinor,900_000);
 assert.equal((await instanceRef.get()).data().currency,'JPY');
 await call('saveCatalog',command('archive-person',{kind:'contact',id:person.id,expectedRevision:1,values:contact({archived:true})}));
 await call('saveCatalog',command('archive-source',{kind:'source',id:cash.id,expectedRevision:1,values:source({active:false})}));
 await assert.rejects(call('createObligation',command('archived-link',loan({contactId:person.id}))),{code:'functions/failed-precondition'});
 await assert.rejects(call('createObligation',command('inactive-source',loan({paymentSourceId:cash.id}))),{code:'functions/failed-precondition'});
 await call('editObligation',command('note-after-archive',{...edit,expectedRevision:3,amountMinor:900_000,currency:'JPY',notes:'Keep historical links'}));
 await call('cancelObligation',command('cancel-1',{obligationId:created.obligationId,expectedRevision:4,reason:'Recorded in error'}));
 assert.equal((await parentRef.get()).data().lifecycle,'cancelled');assert.equal((await parentRef.get()).data().remainingMinor,900_000);assert.equal((await instanceRef.get()).data().closed,true);
 await root.update({accountStatus:'deleting'});
 await assert.rejects(call('createObligation',payload),{code:'functions/failed-precondition'});
}));
test('references belonging to another owner cannot be resolved',async()=>withOwner('alice',async alice=>withOwner('bob',async bob=>{
 const person=await bob.call('saveCatalog',bob.command('bob-contact',{kind:'contact',id:null,expectedRevision:null,values:contact()}));
 await assert.rejects(alice.call('createObligation',alice.command('foreign',loan({contactId:person.id}))),{code:'functions/failed-precondition'});
 assert.equal((await alice.root.collection('obligations').get()).size,0);
})));
