import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import {withOwner} from '../firebase/emulator-tests/support/session.mjs';
const require=createRequire(new URL('../functions/package.json',import.meta.url));
require('firebase-admin/app').initializeApp({projectId:'demo-tally'});
const {Timestamp}=require('firebase-admin/firestore');
const {periodJobId,claimAutomaticJob}=require('./lib/src/jobs/recurring_jobs.js');
const {processAutomatic}=require('./lib/src/recurring/automatic_service.js');
const encode=value=>value instanceof Timestamp?{timestamp:value.toDate().toISOString()}:Array.isArray(value)?value.map(encode):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([key,item])=>[key,encode(item)])):value;
const rule={frequency:'monthly',unit:'months',interval:1,anchorDate:'2026-10-04',preferredDay:4,monthEnd:false,timezone:'Asia/Manila',localDeductionTime:'09:00',startDate:'2026-10-04',endDate:null,ruleVersion:1};
const terms={amountMinor:54900,paymentDate:'2026-10-04',paymentSourceId:null,paymentMethod:'other',notes:''};
const records={};
await withOwner('recurring-fixture',async({call,command,root,user,adminDb})=>{
  records.owner=user.uid;
  const create=patch=>call('createRecurring',command(`create-${Object.keys(records).length}`,{title:'Netflix',description:'Subscription',notes:'',contactId:null,categoryId:'default-subscription',currency:'PHP',amountKind:'fixed',defaultAmountMinor:54900,paymentMode:'automatic',paymentSourceId:null,recurrence:rule,reminderPolicy:{enabled:false,offsetDays:[],localTime:'09:00'},...patch}));
  const get=async(collection,id)=>(await root.collection(collection).doc(id).get()).data();
  const fixed=await create({});records.parent=await get('obligations',fixed.obligationId);records.scheduled=await get('obligationInstances',fixed.firstInstanceId);
  await root.collection('obligationInstances').doc(fixed.firstInstanceId).update({createdAt:Timestamp.fromDate(new Date('2026-10-03T01:00:00Z'))});
  const id=periodJobId(user.uid,fixed.firstInstanceId,'automaticDeduction'),now=new Date();
  const lease=await claimAutomaticJob(id,adminDb,now);await processAutomatic(id,lease.token,adminDb,now);
  records.deducted=await get('obligationInstances',fixed.firstInstanceId);
  const confirmed=await call('confirmDeduction',command('confirm',{obligationId:fixed.obligationId,instanceId:fixed.firstInstanceId,expectedRevision:records.deducted.revision,...terms}));
  records.confirmed=await get('obligationInstances',fixed.firstInstanceId);records.evidence=await get('paymentEvidence',confirmed.evidenceId);records.payment=await get('payments',confirmed.paymentId);
  const failed=await call('reportDeductionFailure',command('fail',{obligationId:fixed.obligationId,instanceId:fixed.firstInstanceId,expectedRevision:records.confirmed.revision,reason:'Card declined'}));
  records.failed=await get('obligationInstances',fixed.firstInstanceId);records.failureAttempt=await get('deductionAttempts',failed.attemptId);
  const variable=await create({title:'Electricity',amountKind:'variable',defaultAmountMinor:350000});records.variable=await get('obligationInstances',variable.firstInstanceId);
  const variableJob=periodJobId(user.uid,variable.firstInstanceId,'automaticDeduction'),variableLease=await claimAutomaticJob(variableJob,adminDb,now);
  await processAutomatic(variableJob,variableLease.token,adminDb,now);records.variableExpected=await get('obligationInstances',variable.firstInstanceId);
  for(const [key,record] of Object.entries(records))if(record&&typeof record==='object'&&record.instanceId)records[key]={...record};
  records.activities=(await root.collection('activities').get()).docs.map(doc=>({id:doc.id,...doc.data()}));
  await writeFile(new URL('../firebase/fixtures/recurring_documents.json',import.meta.url),JSON.stringify(encode(records),null,2)+'\n');
});
