// Rebuild with tool/rebuild_timezones.mjs; this build tool never runs in the app.
import 'dart:convert';
import 'dart:io';

import 'package:timezone/src/tools.dart' show tzfileLocationToNativeLocation;
import 'package:timezone/src/tzdb.dart' show tzdbSerialize;
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/tzdata.dart' as tzfile;

void main(List<String> arguments) {
  if (arguments.length != 3) {
    throw ArgumentError(
      'Expected compiled zoneinfo directory, Dart and JSON output paths.',
    );
  }
  final prefix = '${arguments[0]}/';
  final names =
      Directory(arguments[0])
          .listSync(recursive: true, followLinks: false)
          .where((entry) => entry is File || entry is Link)
          .map((entry) => entry.path.substring(prefix.length))
          .toList()
        ..sort();
  final database = tz.LocationDatabase();
  final jsonLocations = <String, Object>{};
  for (final name in names) {
    final bytes = File('${arguments[0]}/$name').readAsBytesSync();
    final location = tzfileLocationToNativeLocation(
      tzfile.Location.fromBytes(name, bytes),
    );
    database.add(location);
    jsonLocations[name] = {
      'initialOffset': location
          .timeZone(-8640000000000000)
          .offset
          .inMilliseconds,
      'offsets': location.zones
          .map((zone) => zone.offset.inMilliseconds)
          .toList(),
      'transitionAt': location.transitionAt,
      'transitionZone': location.transitionZone,
    };
  }
  final bytes = tzdbSerialize(database);
  final encoded = base64Encode(bytes);
  final lines = <String>[];
  for (var offset = 0; offset < encoded.length; offset += 100) {
    lines.add(
      "  '${encoded.substring(offset, (offset + 100).clamp(0, encoded.length))}'",
    );
  }
  File(arguments[1]).writeAsStringSync(
    '''// GENERATED by tool/rebuild_timezones.mjs. Do not edit.
// IANA 2026c; timezone package 0.11.1; explicit transitions through 2200.
import 'dart:convert';
import 'package:timezone/timezone.dart' as tz;

void initializeTallyTimezones() => tz.initializeDatabase(base64Decode(_data));

const _data =
${lines.join('\n')};
''',
  );
  stdout.writeln(
    'Bundled ${names.length} zones, ${bytes.length} bytes through 2200.',
  );
  final jsonOutput = File(arguments[2]);
  jsonOutput.parent.createSync(recursive: true);
  jsonOutput.writeAsStringSync(
    jsonEncode({
      'version': '2026c',
      'throughYear': 2200,
      'locations': jsonLocations,
    }),
  );
}
